### PR TITLE
Stop players from teleporting back into arena after finished match (fixes #313)

### LINKED ISSUE #313: Players can get back into the arena by teleporting
We have a mob arena with chests and use geSuiteTeleport for teleporting, which has a `/back` command. When players (quickly) use `/back` after leaving the arena, they are teleported back into the arena.

MA already checks if the target location is a warp point, but it is (since the back location is the location the player was previosly teleported to, which is a warp point).

The good news is: I already fixed it, PR is on the way. :+1:

### PR DESCRIPTION
**Pull request by slipcor**

### CODE REVIEW

**Comment by leMaik** [comment]
Was this merged meanwhile? I'm currently updating my server and I'd like to go back to the original version. :wink:

**Comment by garbagemule** [comment]
We're still not entirely sure how best to approach this. It's really difficult to make a proper risk assessment for modifying the teleport code, so it hasn't been pulled, no.

**Comment by leMaik** [comment]
Allright then, just backported the current master to 1.9.4, so that I can wait until we decide to update to 1.10 or 1.11 (or whatever will be around then) :sweat_smile:

**Comment by garbagemule** [comment]
I'll take another stab at this in the April sweep.

**Comment by garbagemule** [comment]
This doesn't solve the problem.

I'll elaborate on #313

**Pull request closed without merging**
