### PR TITLE
switch up / fix the inventory handling to account for the changes in 1.9

### PR DESCRIPTION
**Pull request by slipcor**
Sorry for the auto formatting - seems my IDE wanted that very badly :D

### CODE REVIEW

**Comment by Johandrex** [comment]
Hey, may I please have the jar file?

**Comment by conflictxinside** [comment]
Still seems to throw internal error in latest builds of Spigot.

**Comment by garbagemule** [comment]
Pulled manually.

**Comment by mibby** [comment]
@garbagemule I don't see it on the github repo. :(

**Comment by garbagemule** [comment]
I'm gonna push when all the immediate 1.9 changes have been implemented. Unlike the folks over at Spigot, I don't like the idea of releasing half-done work just for the sake of releasing something.

#maybeslightlysalty

**Pull request closed without merging**
