### PR TITLE
New Abilities!

### PR DESCRIPTION
**Pull request by TheComputerGeek2**
Just hoping to have a few abilities added to the main project as I think people might enjoy them. Mainly adding status effect abilities with the distant, nearby, and target ranges.

The overwhelm ability is supposed to teleport all players and monsters to the player spawn point in the arena, as the name suggests, the purpose is to overwhelm the players with the ability. I think I did the player selection correctly, but let me know if it turns out otherwise.

Overall, let me know what I need to fix before it can be merged, if anything.
Thanks.

### CODE REVIEW

**Comment by garbagemule** [comment]
Great work!

I can't accept this pull request at the moment, because I'm in the process of making some pretty aggressive architectural changes in the plugin - including stuff that would probably make some of these abilities redundant (think "generic, configurable potion effect ability").

If that fails, however, this is a very welcome addition to the quickly aging default repertoire. I would require the following changes:

* Use 4 spaces for indentation, i.e. no tabs.
* Don't break statements or expressions up into multiple lines, i.e. no 80-character max width.
* Documentation of all fields (and consistent vertical spacing between fields).
* Correct access modifiers on fields (private, optionally final).

**Comment by TheComputerGeek2** [comment]
I love the sound of configurable abilities. Is there any possibility that you might post the progress on a new branch so that some of the mob arena addicts can see what is to come and maybe start working on configs/add-ons for it a little early? I would love to be able to start designing abilities for the new system. Also, thanks for the quick and helpful feedback.

**Comment by garbagemule** [comment]
I'll be sure to post updates and information along the way, but there is currently nothing interesting going on - just untangling of the horrible spaghetti that the code base has turned into :cake:

**Comment by TheComputerGeek2** [comment]
Ok, cleaned up the code. Is this what you were looking for in terms of documentation and formatting? Also added the package declarations (whoops)

**Comment by garbagemule** [comment]
Sort of. Take a look at some of the existing abilities to get a feel for how the formatting should look. Documentation should follow the standard JavaDoc format, and comments in the code should be limited to statements and sections of logic that may not convey their intent very clearly.

Also make sure that the code base compiles, and thoroughly test the whole shebang.

**Comment by TheComputerGeek2** [comment]
May I ask what version of CraftBukkit you compiled the current version under? I can't seem to compile your ClassChestCommand class due to LOCKED_CHEST being undefined in the material enum and the getTargetBlock being ambiguous for player. I seem to recall that the getTargetBlock had some changes a while ago.

**Comment by garbagemule** [comment]
I think it was either 1.7.2 or 1.7.9.

**Comment by TheComputerGeek2** [comment]
Well, there haven't been any compile errors on my end and I don't seem to have a 1.7.9 jar anymore, sadly. do you want me to just ignore the ones mentioned above?

**Pull request closed without merging**
