### PR TITLE
Add support for leave/join signs

### PR DESCRIPTION
**Pull request by NathanWolf**
This adds support for creating signs that players can use to join or leave arenas.

The format is similar to leaderboard signs:

```
[MA]<arena>
Leave/Join
```

There is a new permission for this, "mobarena.setup.signs", which is separate from the leaderboard permission.

### CODE REVIEW

**Comment by garbagemule** [comment]
This implementation permits anyone who can create a sign with colored text to place join signs for MobArena anywhere they want. Is that not an issue? From what I can tell, you can't very easily add color to signs in vanilla, but isn't this something a plugin like Essentials would offer?

Note that the only reason this isn't a problem for leaderboards is that leaderboards are actively tracked, while these signs aren't. I suppose we could work some tracking logic in, but it's such a pain to deal 💩

**Comment by NathanWolf** [comment]
Hm good point, I guess maybe an option or permission to turn them off completely if it becomes a problem would be good?

I think tracking them would be overkill, it's pretty rare for normal players to be allowed to create colored signs. I guess alternately checking for placement of the colored sign would work.

**Comment by ct-martin** [comment]
From what I've seen, a `SignChangeEvent` can be used to check when one is placed (& the content specified), and then you can check for permissions if it's got the plugin's special content (and if they don't, cancel the event and send a message). Another thought is that you may want to have them place it w/o colors and then you can add them after (in case they can't add colors). Regex could be useful to support both cases.

**Comment by ct-martin** [comment]
My bad, didn't see the commit attached. If you change the `return` on the permission check with cancelling the event you should be fine.

**Comment by NathanWolf** [comment]
@ct-martin let me know if that recent commit is not what you meant! (Not sure if this is still relevant)

**Comment by ct-martin** [comment]
@NathanWolf at a glance it looks a little different, next time I talk with @garbagemule I'll discuss it with him. Thanks for the work!

**Comment by garbagemule** [comment]
Good candidate for the April sweep!

**Pull request closed without merging**
