### PR TITLE
Simple Change: Allow Ignoring Case When Typing Arena Name

### PR DESCRIPTION
**Pull request by Haileykins**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Documentation
    * [ ] Refactoring
    * [X] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

Just replaced equals(configName) to equalsIgnoreCase(configName) in ArenaMasterImpl line 227

### CODE REVIEW

**Comment by Haileykins** [comment]
@jflory7 Do you know when @garbagemule might be able to get around to it? I have more stuff to toss out, but I want to do them as seperate pull requests because they are non-coordinating changes

**Comment by jflory7** [comment]
@Haileykins I pinged him now in IRC for follow-up. Hopefully will have an answer for you this week! If he doesn't respond, I may merge this in because I really think it's simple and harmless, and I think it's important if you are working on bigger and more exciting things.

This could also be a good time for us to figure out how code reviews should work in the future.

**Comment by Haileykins** [comment]
I would highly agree, the next thing I want to push up is a gamemode 3 type spectator mode, using potion effects to eliminate the need for the barrier effects around the arena, that was done with help from a friend of mine IBCodin

**Comment by Haileykins** [comment]
@jflory7 is there a place we can talk more? Discord or something perhaps?

**Comment by jflory7** [comment]
@Haileykins Good question!

MobArena has an [Internet Relay Chat](https://en.wikipedia.org/wiki/Internet_Relay_Chat) (IRC) channel on the [EsperNet IRC network](https://esper.net/). The channel is `#mobarena`.

If you have never connected to IRC before, you have two options:

* [Web chat](https://esper.net/publicirc.php): Works in a web browser, but only keeps you connected when you have the tab open
* [Matrix/Riot](https://opensource.com/article/17/5/introducing-riot-IRC): Web chat / desktop client / phone app that works with IRC; to connect to our channel, the alias on Riot is `#_espernet_#mobarena:matrix.org`

You can find other members of the development team there. Don't be afraid to say hello!

**Comment by garbagemule** [comment]
Thanks for this PR. I'll give it a whirl in the April sweep.

I need to dig a little deeper on this, because off the top of my head, I can't tell how much a change like this will impact other parts of the entry points (commands, signs, etc.).

The case sensitive nature of MobArena is a huge problem in many aspects, but I think it might be worth actually trying to solve the underlying problem instead of fixing what appears to be a symptom. Perhaps it's worth exploring things like "display names" as an actual thing in the config-file, and maybe moving away from a map-oriented style in the config-file to a list-oriented style. This might help improve clarity. Another possibility could be "fuzzy matching".

PS: MobArena has a Discord, it's in the topic in IRC :)

**Comment by garbagemule** [comment]
I just had a look through the code base, and this method is used in _a lot_ of places. I was a bit worried that a change like this might have some unexpected side-effects, but from what I can tell, the only case that would pose any issues is if people have two arenas with the same name, just different casing, like `bestarena` and `BestArena`. With this change, MobArena would actually skip one of them (the order is arbitrary). I do think this is the right way to go about things, and I think it's perfectly fair to break that one server that might be distinguishing arenas by casing instead of coming up with proper, different names - a release note should be enough of a warning :)

The only thing that nags me is the commit message. The project doesn't have contribution guidelines yet - that's my bad - so it's impossible to know this, but there are a few conditions that I want commit messages to meet. Some are a bit nitpicky/semi-OCD, and others have deeper meaning. I'll make sure to write a CONTRIBUTION.md today so it's all written down.

@Haileykins can you join the MobArena Discord server? I'd like to just try out a few things with this PR, but I don't want the comments section here spammed :P

**Pull request merged**
